#pragma once

#include "Frost/Asset/AssetManager.h"
#include "Frost/Asset/ModelFactory.h"
#include "Frost/Asset/Texture.h"
#include "Frost/Asset/MeshConfig.h"

#include "Frost/Core/Application.h"
#include "Frost/Core/Layer.h"
#include "Frost/Core/LayerStack.h"
#include "Frost/Core/SceneLayer.h"
#include "Frost/Core/Timer.h"
#include "Frost/Core/Window.h"
#include "Frost/Core/Windows/WindowWin.h"

#include "Frost/Event/Events/PauseMenu/PauseEvent.h"
#include "Frost/Event/Events/PauseMenu/ResetEvent.h"
#include "Frost/Event/Events/PauseMenu/UnPauseEvent.h"
#include "Frost/Event/Events/Scene/LoadLevelEvent.h"

#include "Frost/Debugging/Assert.h"
#include "Frost/Debugging/DebugLayer.h"
#include "Frost/Debugging/ImGuiSymbols.h"
#include "Frost/Debugging/Logger.h"
#include "Frost/Debugging/DebugInterface/DebugUtils.h"

#include "Frost/Input/Input.h"

#include "Frost/Physics/Physics.h"
#include "Frost/Physics/PhysicsConfig.h"
#include "Frost/Physics/ShapeFactory.h"

#include "Frost/Scene/Components/Camera.h"
#include "Frost/Scene/Components/Light.h"
#include "Frost/Scene/Components/Meta.h"
#include "Frost/Scene/Components/RigidBody.h"
#include "Frost/Scene/Components/Skybox.h"
#include "Frost/Scene/Components/StaticMesh.h"
#include "Frost/Scene/Components/Transform.h"
#include "Frost/Scene/Components/WorldTransform.h"
#include "Frost/Scene/Components/Billboard.h"
#include "Frost/Scene/Components/UIElement.h"
#include "Frost/Scene/Scene.h"
#include "Frost/Scene/SceneManager.h"

#include "Frost/Renderer/DX11/RendererDX11.h"
#include "Frost/Renderer/PostEffect/ChromaticAberrationEffect.h"
#include "Frost/Renderer/PostEffect/FogEffect.h"
#include "Frost/Renderer/PostEffect/RadialBlurEffect.h"
#include "Frost/Renderer/PostEffect/ToonEffect.h"
#include "Frost/Renderer/PostEffect/ScreenShakeEffect.h"
#include "Frost/Renderer/PostEffect/ColorCorrectionEffect.h"
#include "Frost/Renderer/RendererAPI.h"

#include "Frost/Scripting/Script.h"
#include "Frost/Scripting/ScriptingBridge.h"

#include "Frost/Utils/NoCopy.h"
#include "Frost/Utils/Math/Angle.h"
#include "Frost/Utils/Random.h"
