@echo off
setlocal

:: ==============================================================================
:: CONFIGURATION
:: ==============================================================================

:: Directories to remove from the root
set "ROOT_DIRS_TO_CLEAN=CMakeFiles x64 Debug Release vendor .vs"

:: File extensions or names to remove from the root
set "ROOT_FILES_TO_CLEAN=*.sln *.slnx *.vcxproj *.vcxproj.user *.vcxproj.filters CMakeCache.txt cmake_install.cmake Makefile"

:: Specific directories generated by CMake to remove
set "CMAKE_DIRS_TO_CLEAN=ZERO_CHECK.dir INSTALL.dir ALL_BUILD.dir"

:: Sub-projects to iterate through
set "PROJECT_SUBDIRS=Frost Lab Game Editor SwiftBot"

:: Directories to remove inside sub-projects
set "SUB_DIRS_TO_CLEAN=bin CMakeFiles Debug Release x64"

:: Files to remove inside sub-projects
set "SUB_FILES_TO_CLEAN=*.vcxproj *.vcxproj.filters *.vcxproj.user cmake_install.cmake imgui.ini *.log"

:: ==============================================================================
:: EXECUTION
:: ==============================================================================

echo [INFO] Starting project cleanup...

:: -----------------------------------------------------------------------------
:: 1. Root Directory Cleanup
:: -----------------------------------------------------------------------------

echo [INFO] Cleaning root directory...

:: Remove generic build directories
for %%d in (%ROOT_DIRS_TO_CLEAN%) do (
    if exist "%%d" (
        echo   [CLEAN] Removing directory: %%d
        rmdir /s /q "%%d"
    )
)

:: Remove specific CMake directories
for %%d in (%CMAKE_DIRS_TO_CLEAN%) do (
    if exist "%%d" (
        echo   [CLEAN] Removing CMake directory: %%d
        rmdir /s /q "%%d"
    )
)

:: Remove build files
for %%f in (%ROOT_FILES_TO_CLEAN%) do (
    if exist "%%f" (
        echo   [CLEAN] Removing file: %%f
        del /q "%%f"
    )
)

:: -----------------------------------------------------------------------------
:: 2. Sub-directory Cleanup
:: -----------------------------------------------------------------------------

echo [INFO] Cleaning sub-directories (%PROJECT_SUBDIRS%)...

for %%p in (%PROJECT_SUBDIRS%) do (
    if exist "%%p" (
        pushd "%%p"
        
        :: Clean explicit directories inside sub-project
        for %%d in (%SUB_DIRS_TO_CLEAN%) do (
            if exist "%%d" (
                echo   [%%p] Removing directory: %%d
                rmdir /s /q "%%d"
            )
        )

        :: Clean generic CMake .dir folders
        for /d %%g in (*.dir) do (
            echo   [%%p] Removing CMake target: %%g
            rmdir /s /q "%%g"
        )

        :: Clean build files
        for %%f in (%SUB_FILES_TO_CLEAN%) do (
            if exist "%%f" (
                echo   [%%p] Removing file: %%f
                del /q "%%f"
            )
        )
        
        popd
    ) else (
        echo   [WARN] Sub-directory %%p not found. Skipping.
    )
)

:: -----------------------------------------------------------------------------
:: FINISH
:: -----------------------------------------------------------------------------

echo [INFO] Cleanup finished successfully.
endlocal