#pragma once

#include "Frost/Core/Core.h"

#include <unordered_map>

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

namespace Frost
{
    enum KeyState
    {
        DOWN,
        REPEATED,
        UP
    };

    enum VirtualKeyCode : unsigned int
    {
        K_LBUTTON = VK_LBUTTON,
        K_RBUTTON = VK_RBUTTON,
        K_CANCEL = VK_CANCEL,
        K_MBUTTON = VK_MBUTTON,
        K_XBUTTON1 = VK_XBUTTON1,
        K_XBUTTON2 = VK_XBUTTON2,
        K_BACK = VK_BACK,
        K_TAB = VK_TAB,
        K_CLEAR = VK_CLEAR,
        K_RETURN = VK_RETURN,
        K_SHIFT = VK_SHIFT,
        K_CONTROL = VK_CONTROL,
        K_MENU = VK_MENU,
        K_PAUSE = VK_PAUSE,
        K_CAPITAL = VK_CAPITAL,
        K_KANA = VK_KANA,
        K_HANGUL = VK_HANGUL,
        K_IME_ON = VK_IME_ON,
        K_JUNJA = VK_JUNJA,
        K_FINAL = VK_FINAL,
        K_HANJA = VK_HANJA,
        K_KANJI = VK_KANJI,
        K_IME_OFF = VK_IME_OFF,
        K_ESCAPE = VK_ESCAPE,
        K_CONVERT = VK_CONVERT,
        K_NONCONVERT = VK_NONCONVERT,
        K_ACCEPT = VK_ACCEPT,
        K_MODECHANGE = VK_MODECHANGE,
        K_SPACE = VK_SPACE,
        K_PRIOR = VK_PRIOR,
        K_NEXT = VK_NEXT,
        K_END = VK_END,
        K_HOME = VK_HOME,
        K_LEFT = VK_LEFT,
        K_UP = VK_UP,
        K_RIGHT = VK_RIGHT,
        K_DOWN = VK_DOWN,
        K_SELECT = VK_SELECT,
        K_PRINT = VK_PRINT,
        K_EXECUTE = VK_EXECUTE,
        K_SNAPSHOT = VK_SNAPSHOT,
        K_INSERT = VK_INSERT,
        K_DELETE = VK_DELETE,
        K_HELP = VK_HELP,
        K_0 = '0',
        K_1 = '1',
        K_2 = '2',
        K_3 = '3',
        K_4 = '4',
        K_5 = '5',
        K_6 = '6',
        K_7 = '7',
        K_8 = '8',
        K_9 = '9',
        K_A = 'A',
        K_B = 'B',
        K_C = 'C',
        K_D = 'D',
        K_E = 'E',
        K_F = 'F',
        K_G = 'G',
        K_H = 'H',
        K_I = 'I',
        K_J = 'J',
        K_K = 'K',
        K_L = 'L',
        K_M = 'M',
        K_N = 'N',
        K_O = 'O',
        K_P = 'P',
        K_Q = 'Q',
        K_R = 'R',
        K_S = 'S',
        K_T = 'T',
        K_U = 'U',
        K_V = 'V',
        K_W = 'W',
        K_X = 'X',
        K_Y = 'Y',
        K_Z = 'Z',
        K_LWIN = VK_LWIN,
        K_RWIN = VK_RWIN,
        K_APPS = VK_APPS,
        K_SLEEP = VK_SLEEP,
        K_NUMPAD0 = VK_NUMPAD0,
        K_NUMPAD1 = VK_NUMPAD1,
        K_NUMPAD2 = VK_NUMPAD2,
        K_NUMPAD3 = VK_NUMPAD3,
        K_NUMPAD4 = VK_NUMPAD4,
        K_NUMPAD5 = VK_NUMPAD5,
        K_NUMPAD6 = VK_NUMPAD6,
        K_NUMPAD7 = VK_NUMPAD7,
        K_NUMPAD8 = VK_NUMPAD8,
        K_NUMPAD9 = VK_NUMPAD9,
        K_MULTIPLY = VK_MULTIPLY,
        K_ADD = VK_ADD,
        K_SEPARATOR = VK_SEPARATOR,
        K_SUBTRACT = VK_SUBTRACT,
        K_DECIMAL = VK_DECIMAL,
        K_DIVIDE = VK_DIVIDE,
        K_F1 = VK_F1,
        K_F2 = VK_F2,
        K_F3 = VK_F3,
        K_F4 = VK_F4,
        K_F5 = VK_F5,
        K_F6 = VK_F6,
        K_F7 = VK_F7,
        K_F8 = VK_F8,
        K_F9 = VK_F9,
        K_F10 = VK_F10,
        K_F11 = VK_F11,
        K_F12 = VK_F12,
        K_F13 = VK_F13,
        K_F14 = VK_F14,
        K_F15 = VK_F15,
        K_F16 = VK_F16,
        K_F17 = VK_F17,
        K_F18 = VK_F18,
        K_F19 = VK_F19,
        K_F20 = VK_F20,
        K_F21 = VK_F21,
        K_F22 = VK_F22,
        K_F23 = VK_F23,
        K_F24 = VK_F24,
        K_NUMLOCK = VK_NUMLOCK,
        K_SCROLL = VK_SCROLL,
        K_LSHIFT = VK_LSHIFT,
        K_RSHIFT = VK_RSHIFT,
        K_LCONTROL = VK_LCONTROL,
        K_RCONTROL = VK_RCONTROL,
        K_LMENU = VK_LMENU,
        K_RMENU = VK_RMENU,
        K_BROWSER_BACK = VK_BROWSER_BACK,
        K_BROWSER_FORWARD = VK_BROWSER_FORWARD,
        K_BROWSER_REFRESH = VK_BROWSER_REFRESH,
        K_BROWSER_STOP = VK_BROWSER_STOP,
        K_BROWSER_SEARCH = VK_BROWSER_SEARCH,
        K_BROWSER_FAVORITES = VK_BROWSER_FAVORITES,
        K_BROWSER_HOME = VK_BROWSER_HOME,
        K_VOLUME_MUTE = VK_VOLUME_MUTE,
        K_VOLUME_DOWN = VK_VOLUME_DOWN,
        K_VOLUME_UP = VK_VOLUME_UP,
        K_MEDIA_NEXT_TRACK = VK_MEDIA_NEXT_TRACK,
        K_MEDIA_PREV_TRACK = VK_MEDIA_PREV_TRACK,
        K_MEDIA_STOP = VK_MEDIA_STOP,
        K_MEDIA_PLAY_PAUSE = VK_MEDIA_PLAY_PAUSE,
        K_LAUNCH_MAIL = VK_LAUNCH_MAIL,
        K_LAUNCH_MEDIA_SELECT = VK_LAUNCH_MEDIA_SELECT,
        K_LAUNCH_APP1 = VK_LAUNCH_APP1,
        K_LAUNCH_APP2 = VK_LAUNCH_APP2,
        K_OEM_1 = VK_OEM_1,
        K_OEM_PLUS = VK_OEM_PLUS,
        K_OEM_COMMA = VK_OEM_COMMA,
        K_OEM_MINUS = VK_OEM_MINUS,
        K_OEM_PERIOD = VK_OEM_PERIOD,
        K_OEM_2 = VK_OEM_2,
        K_OEM_3 = VK_OEM_3,
        K_GAMEPAD_A = VK_GAMEPAD_A,
        K_GAMEPAD_B = VK_GAMEPAD_B,
        K_GAMEPAD_X = VK_GAMEPAD_X,
        K_GAMEPAD_Y = VK_GAMEPAD_Y,
        K_GAMEPAD_RIGHT_SHOULDER = VK_GAMEPAD_RIGHT_SHOULDER,
        K_GAMEPAD_LEFT_SHOULDER = VK_GAMEPAD_LEFT_SHOULDER,
        K_GAMEPAD_LEFT_TRIGGER = VK_GAMEPAD_LEFT_TRIGGER,
        K_GAMEPAD_RIGHT_TRIGGER = VK_GAMEPAD_RIGHT_TRIGGER,
        K_GAMEPAD_DPAD_UP = VK_GAMEPAD_DPAD_UP,
        K_GAMEPAD_DPAD_DOWN = VK_GAMEPAD_DPAD_DOWN,
        K_GAMEPAD_DPAD_LEFT = VK_GAMEPAD_DPAD_LEFT,
        K_GAMEPAD_DPAD_RIGHT = VK_GAMEPAD_DPAD_RIGHT,
        K_GAMEPAD_MENU = VK_GAMEPAD_MENU,
        K_GAMEPAD_VIEW = VK_GAMEPAD_VIEW,
        K_GAMEPAD_LEFT_THUMBSTICK_BUTTON = VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON,
        K_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON,
        K_GAMEPAD_LEFT_THUMBSTICK_UP = VK_GAMEPAD_LEFT_THUMBSTICK_UP,
        K_GAMEPAD_LEFT_THUMBSTICK_DOWN = VK_GAMEPAD_LEFT_THUMBSTICK_DOWN,
        K_GAMEPAD_LEFT_THUMBSTICK_RIGHT = VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT,
        K_GAMEPAD_LEFT_THUMBSTICK_LEFT = VK_GAMEPAD_LEFT_THUMBSTICK_LEFT,
        K_GAMEPAD_RIGHT_THUMBSTICK_UP = VK_GAMEPAD_RIGHT_THUMBSTICK_UP,
        K_GAMEPAD_RIGHT_THUMBSTICK_DOWN = VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN,
        K_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT,
        K_GAMEPAD_RIGHT_THUMBSTICK_LEFT = VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT,
        K_OEM_4 = VK_OEM_4,
        K_OEM_5 = VK_OEM_5,
        K_OEM_6 = VK_OEM_6,
        K_OEM_7 = VK_OEM_7,
        K_OEM_8 = VK_OEM_8,
        K_OEM_102 = VK_OEM_102,
        K_PROCESSKEY = VK_PROCESSKEY,
        K_PACKET = VK_PACKET,
        K_ATTN = VK_ATTN,
        K_CRSEL = VK_CRSEL,
        K_EXSEL = VK_EXSEL,
        K_EREOF = VK_EREOF,
        K_PLAY = VK_PLAY,
        K_ZOOM = VK_ZOOM,
        K_NONAME = VK_NONAME,
        K_PA1 = VK_PA1,
        K_OEM_CLEAR = VK_OEM_CLEAR
    };

    class FROST_API Keyboard
    {
    public:
        KeyState GetKeyState(const VirtualKeyCode keyCode) const;
        void SetKeyState(const VirtualKeyCode keyCode, const KeyState newState);
        bool IsKeyDown(const VirtualKeyCode keyCode) const;
        bool IsKeyPressed(const VirtualKeyCode keyCode) const;
        void Update();

    private:
        std::unordered_map<VirtualKeyCode, KeyState> _keyStates;
    };
} // namespace Frost
